# Generated by Django 4.0.3 on 2022-04-07 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.TextField()),
                ('id_tipo_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.tipouser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inmuebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_inmueble', models.TextField()),
                ('descripcion', models.TextField()),
                ('m2_construido', models.FloatField()),
                ('m2_terreno', models.FloatField()),
                ('numero_estacionamientos', models.IntegerField()),
                ('numero_banos', models.IntegerField(default=0)),
                ('numero_hab', models.IntegerField(default=0)),
                ('direccion', models.TextField()),
                ('precio_mensual', models.FloatField()),
                ('estado', models.BooleanField(default=False)),
                ('id_comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.comuna')),
                ('id_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.region')),
                ('id_tipo_inmueble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.tipoinmueble')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
