# Generated by Django 4.0.3 on 2022-04-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0002_alter_profile_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmuebles',
            name='estado',
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='nombre_inmueble',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='numero_banos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='numero_estacionamientos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='numero_hab',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='precio_mensual',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='correo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
